server:
  port: 8082

spring:
  application:
    name: servicio-gestion

  datasource:
    url: jdbc:h2:mem:gestiondb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true        # Activa la consola web de H2
      path: /h2            # Ruta para acceder (http://localhost:8082/h2)

  jpa:
    hibernate:
      ddl-auto: update     # Crea o actualiza las tablas autom√°ticamente
    show-sql: true          # Muestra las consultas SQL en la consola
    properties:
      hibernate:
        format_sql: true
